### PR TITLE
cleaned up load_dataset, created a cleaning + EDA script

### PR DESCRIPTION
**Pull request by smwatts**
I made a data cleaning script by:

- Selecting the final grade & sex column
- Dividing the final grade by 20 to get the final grade % (grades were originally stored as values scored in the course from 0 to 20) 
- Naming columns as sex and math_final_grade

Please let me know what you think!

### CODE REVIEW

**Comment by smwatts** [comment]
I made a script that creates a histogram of the student's final scores, shown below:

hist-student-math-perf

Let me know if you'd like to represent the data in another way :)

**Review by ellognea — COMMENTED** [review]
Thanks Sarah ! Some clarifying questions:

- why do we need the  final grade % column ? I was thinking we could use the final grade column (G3) to calculate the average grade using the mean() function... In this case I would have just renamed the column (G3)... Let me know what you think.

- EDA script:  I was thinking about a violin plot + jitter plot + mean and/or CI ( like the iris plot in 561 lab1).

Let me know what you think. I can merge and update the scripts if that would work better.

**Comment by smwatts** [comment]
I think using the final_grade_% is better because the G3 column represents grades out of 20.

So you'll have student 1's G3 grade as 8, student 2's G3 grade as 12. I think it's difficult to visualize and understand what these numbers mean so I converted them to grades.

This way you can see student 1 has a 40% and student 2 has a 60% in math.

Since we just have a linear transformation (/20 and *100) this won't impact the means and CIs we are calculating.

**Comment by smwatts** [comment]
I created the jitter, violin plot with the mean & confidence intervals

violin-student-math-perf

**Comment by ellognea** [comment]
looks awesome !

**Pull request merged**
